### ISSUE TITLE
Crash with multiple categories and ordered bars

### ISSUE THREAD

**Issue by hnguye34** [cleroux/flot.barlabels#5]
Hello,

When I am using ordered bars (to have multiple categories side by side), all label are "Nan".
Because the series.data[i][2] can be empty and so "b" variable is undefined.
_var b = series.data[i].length > 2  ? _series.data[i][2_] : 0;_  (line 59)

Could you add a check to prevent this crash please ?
(Something like for example): var b = series.data[i].length > 2 _&& series.data[i][2_] ? series.data[i][2] : 0; )

Thank you for your help !

**Comment by cleroux** [comment]
Thank you for reporting this and the suggested fix.  I have pushed the commit to master.
