### ISSUE TITLE
Labels disappear when resizing the screen

### ISSUE THREAD

**Issue by hnguye34** [cleroux/flot.barlabels#7]
Hello Cédric,

When resizing the screen, the labels disappear. (And the same issue replicated when the graph drawn multiples times...)

The cause seems to be that when deleting the labels from Dom (see below), the cache inside of Canvas class still keeping them, becomes invalid then. 

`$(placeholder).find(".flot-bar-labels > .flot-bar-label").remove();`

[https://github.com/cleroux/flot.barlabels/blob/dae966dacd6bc256b136bcbdb48d395a7306d502/jquery.flot.barlabels.js#L38](url)

Could you so remove them from the cache when delelting from Dom, please ?
For example, something as following:

>  var layer = "flot-bar-labels";
>  if (barLabels == null) {
>                  barLabels = new Canvas("flot-bar-labels", placeholder);
>             }
>             else {
>                 barLabels.removeText(layer);
>                 barLabels.render();
>             }
>             $(placeholder).find(".flot-bar-labels > .flot-bar-label").remove();

as removeText() will only make the texts inactive, render() method will remove actually from the cache.

I have tested this fix.

Possible alternative not tested: in the current version of Flot, Canvas.clearCache() method could remove everything (without specifing the layer). My Flot version too old and this method not existing, so I could not check whether this method could also fix.

Thank you !

**Comment by cleroux** [comment]
Thank you for this information!
This sounds similar to something that was reported in #3.
Can you confirm which version of Flot you are using and whether you are using Flot's resize plugin?
I will take a closer look at this in a few days.

**Comment by cleroux** [comment]
Also, you may submit a pull request if you wish since it seems you already have a fix.  Pull requests are welcome and it would be very much appreciated.

**Comment by cleroux** [comment]
Thanks for submitting the fix in #8.  Cheers!
